// <auto-generated />
using System;
using BudgetControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605190954_CommercialModalidadHitosPagos")]
    partial class CommercialModalidadHitosPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAcuerdo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_acuerdo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total");

                    b.Property<string>("NumeroAcuerdo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_acuerdo");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.ToTable("acuerdos_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<int>("ModalidadCobro")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad_cobro");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_actual");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_original");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId", "ViaOperacion")
                        .IsUnique();

                    b.ToTable("acuerdos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteAcuerdoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<DateTime>("FechaAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ajuste");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<decimal>("MontoAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_anterior");

                    b.Property<decimal>("MontoNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_nuevo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("TipoAjuste")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_ajuste");

                    b.Property<string>("UsuarioAjuste")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_ajuste");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("ajustes_acuerdos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteCuotaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<int>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<DateTime>("FechaAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ajuste");

                    b.Property<DateTime?>("FechaVencimientoAnterior")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento_anterior");

                    b.Property<DateTime?>("FechaVencimientoNueva")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento_nueva");

                    b.Property<decimal?>("ImporteAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_anterior");

                    b.Property<decimal?>("ImporteNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_nuevo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("PlanPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_pago_id");

                    b.Property<int>("TipoAjuste")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_ajuste");

                    b.Property<string>("UsuarioAjuste")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_ajuste");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.HasIndex("CuotaComercialId");

                    b.HasIndex("PlanPagoId");

                    b.ToTable("ajustes_cuotas_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AplicacionPagoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aplicacion");

                    b.Property<int?>("HitoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("hito_comercial_via_id");

                    b.Property<decimal>("ImporteAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_aplicado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PagoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("pago_comercial_id");

                    b.Property<int>("TipoImputacion")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_imputacion");

                    b.Property<string>("UsuarioAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_aplicacion");

                    b.HasKey("Id");

                    b.HasIndex("CuotaComercialId");

                    b.HasIndex("HitoComercialViaId");

                    b.HasIndex("PagoComercialId");

                    b.ToTable("aplicaciones_pago_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.ClienteReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes_referencia", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal>("ImporteOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_original");

                    b.Property<decimal>("ImportePagado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_pagado");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("integer")
                        .HasColumnName("numero_cuota");

                    b.Property<int>("PlanPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_pago_id");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_pendiente");

                    b.Property<int>("TipoCuota")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cuota");

                    b.HasKey("Id");

                    b.HasIndex("PlanPagoId");

                    b.ToTable("cuotas_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_referencia");

                    b.Property<decimal>("ImporteAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_aplicado");

                    b.Property<decimal>("ImporteEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_estimado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("hitos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.ObraReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_obra");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.HasKey("Id");

                    b.ToTable("obras_referencia", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_total");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medio_pago");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrigenPago")
                        .HasColumnType("integer")
                        .HasColumnName("origen_pago");

                    b.Property<int>("TipoImputacion")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_imputacion");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("pagos_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_cuotas");

                    b.Property<DateTime>("FechaPrimerVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_primer_vencimiento");

                    b.Property<decimal>("MontoAnticipo")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_anticipo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periodicidad");

                    b.Property<bool>("TieneAnticipo")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_anticipo");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialViaId")
                        .IsUnique();

                    b.ToTable("planes_pago", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.VinculacionFacturaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<string>("FacturaExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factura_externa_id");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vinculacion");

                    b.Property<decimal>("ImporteVinculado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_vinculado");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_factura");

                    b.HasKey("Id");

                    b.HasIndex("CuotaComercialId");

                    b.ToTable("vinculaciones_factura_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany("Vias")
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteAcuerdoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Ajustes")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteCuotaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("Ajustes")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.PlanPago", "PlanPago")
                        .WithMany()
                        .HasForeignKey("PlanPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");

                    b.Navigation("CuotaComercial");

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AplicacionPagoComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BudgetControl.Api.Models.Commercial.HitoComercialVia", "HitoComercialVia")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("HitoComercialViaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BudgetControl.Api.Models.Commercial.PagoComercial", "PagoComercial")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuotaComercial");

                    b.Navigation("HitoComercialVia");

                    b.Navigation("PagoComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.PlanPago", "PlanPago")
                        .WithMany("Cuotas")
                        .HasForeignKey("PlanPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Hitos")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany("Pagos")
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Pagos")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithOne("PlanPago")
                        .HasForeignKey("BudgetControl.Api.Models.Commercial.PlanPago", "AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.VinculacionFacturaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("VinculacionesFactura")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuotaComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.UserRole", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercial", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Vias");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Hitos");

                    b.Navigation("Pagos");

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Aplicaciones");

                    b.Navigation("VinculacionesFactura");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
